# Generated by Django 5.0.4 on 2024-04-16 20:04

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('tvoc', models.FloatField(null=True)),
                ('hcho', models.FloatField(null=True)),
                ('pm2_5', models.FloatField(null=True)),
                ('pm10', models.FloatField(null=True)),
                ('co2', models.FloatField(null=True)),
                ('capture_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'AQI Entry',
                'verbose_name_plural': 'AQI Entries',
            },
        ),
    ]
